#cloud-config

fqdn: {{ hostname }}
ssh_pwauth: false

users:
  - name: almalinux
    groups: [adm, systemd-journal]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHIDqsqUe3mwXCZvi8ur+Okv5zWcNb9jox3RIs7Te7JO
  - name: nick
    groups: [wheel]
    shell: /bin/zsh
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHIDqsqUe3mwXCZvi8ur+Okv5zWcNb9jox3RIs7Te7JO

yum_repos:
  docker-ce-stable:
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
    name: Docker CE Stable - $basearch
  epel:
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/Everything/$basearch/
    enabled: true
    gpgcheck: true
    gpgkey: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
    name: EPEL

package_update: true
package_upgrade: true
packages:
  - zsh
  - git
  - python3
  - python3-pip
  - vim-enhanced
  - wget
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
  - docker-buildx-plugin
  - rsync
  - htop
  - iotop

write_files:
  - path: /home/nick/.zshrc
    content: |
      unsetopt beep
      alias h=history
      alias grep=egrep
      alias ll='ls -lah'
  - path: /etc/systemd/coredump.conf.d/disable.conf
    content: |
      [Coredump]
      Storage=none
      ProcessSizeMax=0
  - path: /boot/config.txt
    content: |
      # PoE Hat Fan Speeds
      dtparam=poe_fan_temp0=50000
      dtparam=poe_fan_temp1=60000
      dtparam=poe_fan_temp2=70000
      dtparam=poe_fan_temp3=80000

runcmd:
  - mkdir /opt/services
  - setenforce 0
  - systemctl stop firewalld && systemctl disable firewalld
  - systemctl start docker && systemctl enable docker
