---
- name: Create service dir
  register: svc_path
  file:
    path: /opt/services/13ft
    state: directory

- name: Copy compose file
  copy:
    src: docker-compose.yml
    dest: "{{ svc_path.path }}"
  notify: Recreate containers
