proxmox_node:
  hosts:
    10.0.10.10:

unifi_rpi:
  hosts:
    10.0.10.3

secondary_dns_rpi:
  hosts:
    10.0.10.4

rpi:
  children:
    caddy_pi:
    secondary_dns_rpi:

docker_hosts:
  hosts:
    10.0.10.8
