proxmox_node:
  hosts:
    10.0.10.10:

primary_pihole:
  hosts:
    10.0.10.3:

secondary_pihole:
  hosts:
    10.0.10.4:

dns:
  children:
    primary_pihole:
    secondary_pihole:

docker_hosts:
  hosts:
    10.0.10.9:

rpi_4:
  hosts:
    10.0.10.4
