proxmox_node:
  hosts:
    10.0.10.10:

primary_rpi:
  hosts:
    10.0.10.3:

secondary_rpi:
  hosts:
    10.0.10.4:

rpi:
  children:
    primary_rpi:
    secondary_rpi:

docker_hosts:
  hosts:
    10.0.10.9:
