---
- name: Create service dir
  register: svc_path
  file:
    path: /opt/services/vikunja
    state: directory

- name: Copy nginx conf
  copy:
    src: nginx.conf
    dest: "{{ svc_path.path }}"
  notify: Recreate containers

- name: Template compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ svc_path.path }}/docker-compose.yml"
  notify: Recreate containers

