---
- name: Configure proxmox host
  hosts: proxmox_node
  become: true
  remote_user: root
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - virt-manager
          - xorriso
          - guestfs-tools
          - sudo
          - python3
          - python3-pip
