---
- name: Configure main pi
  hosts: unifi_rpi
  become: true
  remote_user: almalinux
  gather_facts: false
  roles:
    - pihole
    - unifi

- name: Configure secondary pi
  hosts: secondary_dns_rpi
  become: true
  remote_user: almalinux
  gather_facts: false
  roles:
    - pihole
