---
- name: Configure local env
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Add hashicorp key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
        state: present

    - name: Add hashicorp repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com focal main
        state: present

    - name: Install tenv
      ansible.builtin.apt:
        deb: https://github.com/tofuutils/tenv/releases/download/v3.2.2/tenv_v3.2.2_amd64.deb

    - name: Install packages
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
        update_cache: true
        name:
          - git
          - packer
          - golang
          - python3
          - python3-pip
