---
version: "3.8"
services:
  unifi-controller:
    container_name: controller
    image: lscr.io/linuxserver/unifi-network-application:7.5.187-ls11
    volumes:
      - ./unifi:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MONGO_USER=unifi
      - MONGO_PASS={{ passfile.content | b64decode | trim }}
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
    restart: unless-stopped

  unifi-db:
    image: docker.io/mongo:4.4.18
    container_name: mongo
    volumes:
      - ./mongo:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
    restart: unless-stopped
