---
- name: Create service dir
  register: svc_path
  file:
    path: /opt/services/ladder
    state: directory

- name: Copy rules and forms files
  get_url:
    url: "{{ item.src }}"
    dest:  "{{ item.dest }}"
  notify: Recreate ladder containers
  with_items:
  - src: https://github.com/everywall/ladder/blob/main/ruleset.yaml
    dest: "{{ svc_path.path }}/ruleset.yml"
  - src: https://github.com/everywall/ladder/blob/main/handlers/form.html
    dest: "{{ svc_path.path }}/ruleset.yml"

- name: Copy compose file
  copy:
    src: docker-compose.yml
    dest: "{{ svc_path.path }}"
  notify: Recreate ladder containers
