---
- name: Create service dir
  register: svc_path
  file:
    path: /opt/services/ladder
    state: directory

- name: Copy compose file
  copy:
    src: docker-compose.yml
    dest: "{{ svc_path.path }}/docker-compose.yml"
  notify: Recreate containers
