---
version: "3.8"
services:
  ladder:
    image: ghcr.io/everywall/ladder:v0.0.17
    container_name: ladder
    ports:
      - 8082:8080
    environment:
      - RULESET=/app/ruleset.yaml
      - LOG_URLS=true
    volumes:
      - ./ruleset.yml:/app/ruleset.yaml
    restart: unless-stopped
